# Configurações gerais
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  freemarker:
    cache: ${FREEMARKER_CACHE:false}
    template-loader-path: classpath:/templates/
    settings:
      datetime_format: "dd/MM/yyyy HH:mm"

# Configurações do servidor
server:
  port: ${PORT:8080}
  servlet:
    context-path: /

# Segurança básica (ajuste para produção!)
  security:
    user:
      name: ${ADMIN_USER:admin}
      password: ${ADMIN_PASSWORD:senhaSegura123}